version: '3'
 
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
      - TZ=Asia/Shanghai
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "path.repo=/data/backups"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/es01/data:/usr/share/elasticsearch/data
      - /data/backups/es:/data/backups
    ports:
      - 9200:9200
    restart: always
    networks:
      - esnet
 
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es02
    environment:
      - TZ=Asia/Shanghai
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "path.repo=/data/backups"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/es02/data:/usr/share/elasticsearch/data
      - /data/backups/es:/data/backups
    restart: always
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    depends_on:
      - es01
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=http://172.16.0.70:9200
 
networks:
  esnet:
    driver: bridge