server {
    listen 8002;

    server_name 127.0.0.1;


    access_log /data/wwwlogs/lca_access_nginx.log;
    error_log /data/wwwlogs/lca_access_error_nginx.log;

   # 静态资源根目录（指向 dist 文件夹）
    root /opt/lca/manage/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html; # 支持 Vue Router 的 history 模式
    }

    # 处理静态资源（JS/CSS/图片等）
    location /assets/ {
        alias /opt/lca/manage/dist/assets/;
        expires 1y;
        add_header Cache-Control "public";
    }

   location /api {
      proxy_pass http://127.0.0.1:8808; #后端接口地址
      proxy_set_header Host $proxy_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Authorization $http_authorization;

    }

    # 禁止访问 .git 等敏感文件
    location ~ /\.(?!well-known) {
       deny all;
    }


}