version: "3"
services:
  mysql:
    image: mysql:8.0
    hostname: mysql8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: max2024

    volumes:
      - /data/mysql:/var/lib/mysql
