# Redis Sentinel 配置
# 必须在 sentinel monitor 之前开启 hostname 解析支持（Redis 6.2+）
SENTINEL resolve-hostnames yes
SENTINEL announce-hostnames yes
port 26379
sentinel monitor lca-master redis-master 6379 2
sentinel auth-pass lca-master lca2024
sentinel down-after-milliseconds lca-master 5000
sentinel failover-timeout lca-master 10000
sentinel parallel-syncs lca-master 1
